### PR TITLE
Remove SearchSupported property from value list annotations

### PR DESCRIPTION
**Pull request by c-kobo**
The combination of ValueListFixedValues and SearchSupported is not
supported by the UI5 OData Model. VH breaks if both would be defined at the same time.
As entity searchability defaults to true anyways if SearchSupported property is not defined,
it can be omitted.

### CODE REVIEW

**Comment by stewsk** [comment]
Hi @c-kobo ,
fine with me. Just for clarification:
* what is "VH"?
* you wrote "combination of ValueListFixedValues and SearchSupported is not supported" - even if these two are used in different annotations?

And: I rebased the change as it was out of date, and now the "license/cla" check complains - don't know why. Nevertheless: would you sign the funny license agreement again?

**Comment by c-kobo** [comment]
- VH = value help
- yes, in this case annotations are merged in an additive manner, even if defined separately.

**Comment by stewsk** [comment]
> VH = value help

Ok - should have been able to figure that out by myself ...

@c-kobo : you still need to sign that license thingy, it appears

**Comment by c-kobo** [comment]
Hi @stewsk ,
signing done.

**Pull request merged**
