### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by c-kobo**
bumbing UI5 version to latest to fix dynamic expression evaluation for OperationAvailable 
Synchronizing UX spec version to UI5 version for proper Fiori tools support

### CODE REVIEW

**Comment by stewsk** [comment]
Currently cannot be merged, see https://github.com/SAP-samples/cap-sflight/pull/466

**Comment by drktfl** [comment]
#466 is resolved now

**Comment by stewsk** [comment]
@c-kobo : "fix dynamic expression evaluation for OperationAvailable" - do you remember what exactly did not work?

@drktfl or @c-kobo : what UI5 version should we use now?

**Comment by drktfl** [comment]
I think this should be ok now. We have been using a more recent version for a while already anyway.

**Pull request merged**
