### PR TITLE
Migrate to Typescript

### PR DESCRIPTION
**Pull request by Akatuoro**
- migrate srv to typescript
- include @cds/typer for generated types -> converted some queries to fluent API
- use ts-jest for tests
- use typescript build task for mta deployment

Using tsx for faster local development cycles compared to ts-node.

Also, to get all the tests green:
- mocha with tsx (needs tsx installed locally)
- linting for both js and ts files
- adjusted workflow to install the global dependencies (@sap/cds-dk, typescript, tsx) and run cds-typer - same as local setup steps

### CODE REVIEW

**Comment by chgeo** [comment]
@Akatuoro locally I get errors like
```
Error: ../../node_modules/@types/mocha/index.d.ts(2651,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'.
```

But don't see them in the pipeline.  Do you know why?

**Comment by chgeo** [comment]
Deleted `../../node_modules/@types/mocha/` and the error was gone.  Maybe an issue w/ my monorepo cap/dev setup.  Never mind.

**Review by chgeo — APPROVED** [review]
Cool.  Thanks!

**Comment by stewsk** [comment]
@Akatuoro Build parts of the mta.yamls can stay as they are?

**Comment by Akatuoro** [comment]
> @Akatuoro Build parts of the mta.yamls can stay as they are?

Yes, the typescript specific config is part of the cds build tasks

**Pull request merged**
