### PR TITLE
end to end kyma deployment test for sflight app (Java & Node)

### PR DESCRIPTION
**Pull request by 22shubham22**
Adding Node and java sflight examples end to end kyma test

Co-authored-by: AnaghaDAnanth <63648277+AnaghaDAnanth@users.noreply.github.com>
Co-authored-by: I526683 <shubham.anand@sap.com>

### CODE REVIEW

**Comment by AnaghaDAnanth** [comment]
Hi @chgeo, 
Please let us know if any changes need to be made. Thank you!

**Comment by chgeo** [comment]
@uwe-klinger can you review this as a Kyma expert?  Or involve someone from our team.

**Review by uwe-klinger — APPROVED** [review]

**Review by chgeo — CHANGES_REQUESTED** [review]
@22shubham22 can you show in this PR that the workflow works?  I have assigned a deploy-kyma label, but the job is still skipped.

**Comment by 22shubham22** [comment]
> @22shubham22 can you show in this PR that the workflow works? I have assigned a deploy-kyma label, but the job is still skipped.
> 
> It might be that it's because of your PR comes from a fork. If yes, please join the SAP-samples org, and redo the PR from this repo.

@chgeo whom should i reach out to get access to sap samples org ??

**Comment by chgeo** [comment]
@22shubham22 please go to https://portal.opensource.tools.sap/, join the SAP-samples org.  After that, I can add you to the team for this repo.

**Comment by MrShubham22** [comment]
> @22shubham22 please go to https://portal.opensource.tools.sap/, join the SAP-samples org. After that, I can add you to the team for this repo.

I have joined sap-samples org . Can you please add me as contributor to this repo? 

Thanks

**Comment by MrShubham22** [comment]
> It seems you are not: image
> 
> Make sure to accept the invitation!

22shubham22 is my personal id . 

MrShubham22 is the id i made that i connected with sap id and joined sap samples org .

**Comment by chgeo** [comment]
I see.  Done.

So then please redo the PR with your new user, not using a fork.

**Pull request closed without merging**
