### PR TITLE
Use edmx-expressions for controlling availability of actions

### PR DESCRIPTION
**Pull request by stewsk**

### CODE REVIEW

**Comment by danjoa** [comment]
Would be cool if we could eliminate that UI code from service layer

**Comment by c-kobo** [comment]
@stewsk fyi, we are we are currently working on a fix in sap.fe to support edmx expressions on OperationAvailable.

**Comment by stewsk** [comment]
@c-kobo : do you have an estimate when this fix would be externally available?

**Comment by c-kobo** [comment]
@stewsk we just passed DC for UI5 1.92, so should be available with UI5 1.93 (RTC 12.08.)

**Comment by stewsk** [comment]
Hi @c-kobo , 
which dependency in https://github.com/SAP-samples/cap-sflight/blob/main/app/travel_processor/package.json does this refer to?

**Comment by c-kobo** [comment]
Hi @stewsk ,

the used  UI5 version is not defined by a dependency in the package.json.
For a local sandbox setup, the used ui5 version is defined in the index.html.
https://github.com/SAP-samples/cap-sflight/blob/9c70c3ab199baa6f12300ce65a278324d2084263/app/travel_processor/webapp/index.html#L41
For the url https://ui5.sap.com/resources/sap-ui-core.js (latest public version), this is currently version 1.93.0.
By navigating to https://ui5.sap.com, you get the version written in the top right corner.
image

In order to define a specific ui5 version, you can change that url e.g. to https://ui5.sap.com/1.92.2/resources/sap-ui-core.js
image

For deployment, the ui5 version is afaik defined in the portal site CommonDataModel.json file, which seems to have been deleted by @drktfl though.

**Comment by stewsk** [comment]
UI5 now should be able to handle expressions in `OperationAvailable`, but CAP Java (to be precise: Olingo) doesn't support the dynamic expressions yet. BLI: https://sapjira.wdf.sap.corp/browse/TECHCOREXS2-2746

**Comment by stewsk** [comment]
Feature now supported in Java stack with ds.services.version 1.24.0

**Comment by stewsk** [comment]
@renejeglinsky @danjoa fyi: OData expressions to be used in SFlight

**Comment by rjayasinghe** [comment]
a bit late to the party, but this is really nice! 👍🏾

**Pull request merged**
