### PR TITLE
use java 17 as default

### PR DESCRIPTION
**Pull request by rjayasinghe**
Since cds-services 1.32.0 the new default is Java 17 (older versions are still supported). Would go for 17 here as this is a prominent sample app and we want and have to promote the usage of Java 17 since it will be mandatory in the upcoming cds-services 2.0 release.

Also adding Java 20 (which has just been released) to the build pipeline configuration.

### CODE REVIEW

**Comment by rjayasinghe** [comment]
@BraunMatthias @stewsk set Java version to 17 to be on par with CAP Java Bookshop https://github.com/SAP-samples/cloud-cap-samples-java/commit/c4a6d99d085fa8ab0fefc2f411894be37282731f

Also prepare newer version by introducing a Java 20 CI workflow.

**Review by stewsk — APPROVED** [review]

**Comment by stewsk** [comment]
Hi @BraunMatthias  - ok to merge this?

**Review by BraunMatthias — COMMENTED** [review]
I'd assume changes in [mta-java.yaml](https://github.com/SAP-samples/cap-sflight/blob/main/mta-java.yaml) for JDK 17 as well

**Review by BraunMatthias — APPROVED** [review]
would be good to test on CF in addition

**Comment by stewsk** [comment]
Hi @rjayasinghe ,
in file README-Kyma-Runtime.md there is the line
```
     --env BP_JVM_VERSION=11
```
-> should this also be adjusted?

In addition, in th elist of checks there appears a "build(11)" which is never executed - do you know what that is?

**Comment by stewsk** [comment]
> I can only see the checks for 17 and 20.

you need to scroll down the list of checks

**Comment by rjayasinghe** [comment]
> > Hi @rjayasinghe , in file README-Kyma-Runtime.md there is the line
> > ```
> >      --env BP_JVM_VERSION=11
> > ```
> > -> should this also be adjusted?
> > I'll check if and how we need to adjust this.

Called the pack command locally with BP_JVM_VERSION=17 and it worked like a charm. Started the built container image and verified the Java version manually.

**Comment by rjayasinghe** [comment]
> No, I meant the list of checks here on the "main" page:
> 
> image

Ah, I see. I have no idea where this is coming from. @chgeo can you explain this? Or is it just a GH Actions glitch? I would rather give it a try and merge this PR and see if it disappears from the list afterwards.

**Comment by chgeo** [comment]
The 11.x entry was set to be mandatory in the [protection rules for the `main` branch](https://github.com/SAP-samples/cap-sflight/settings/branch_protection_rules/22051552), hence it appears even if no longer active.  I have removed it there.

**Pull request merged**
