### PR TITLE
MTA configuration

### PR DESCRIPTION
**Pull request by drktfl**
Initial MTA configuration for deployment to CloudFoundry. 

Points to be clarified and tested:

- [x] The MTA contains the UAA, but the service does not use it yet; it runs unprotected.
- [x] Check whether all services are available in trial accounts, for instance - the portal service most likely is not.
- [x] ...

### CODE REVIEW

**Comment by chgeo** [comment]
Can we move `router` and `portal` folders to `app/`?  Would reduce top-level folders.  And `app'/router` is nice to read :)

**Comment by drktfl** [comment]
to do: check https://help.sap.com/viewer/8c8e1958338140699bd4811b37b82ece/Cloud/en-US/ea482cc0edda43438d0b255424e2a10f.html

**Comment by rjayasinghe** [comment]
@stewsk For the Java part you might need be some additional configuration wrt to JDK versions:

```
  env:
      JBP_CONFIG_COMPONENTS: '{jres: ["JavaBuildpack::Jre::SapMachineJRE"]}'
      JBP_CONFIG_SAP_MACHINE_JRE: '{ jre: { version: 11.+ } }'
```

I did not test that myself but you could use this as a starting point.

**Comment by stewsk** [comment]
Hi @rjayasinghe ,
thanks. I also found that config somewhere and tried it out on Friday - it worked.
The deployment then did not complain about version mismatch anymore, but it reported a timestamp mismatch for the java classes.

**Comment by rjayasinghe** [comment]
> Hi @rjayasinghe ,
> thanks. I also found that config somewhere and tried it out on Friday - it worked.
> The deployment then did not complain about version mismatch anymore, but it reported a timestamp mismatch for the java classes.

You could try to completely underlay the Java part and than redeploy it with the correct JDK version setting.

**Comment by stewsk** [comment]
> You could try to completely underlay the Java part

What do you mean by this / how does this work?

**Comment by rjayasinghe** [comment]
> > You could try to completely underlay the Java part
> 
> What do you mean by this / how does this work?

Sorry, autocorrect fooled me. It should mean "undeploy".  I think it should be sth like `cf undeploy <MTA_ID>`.

**Comment by stewsk** [comment]
@drktfl / @chgeo : can we merge this PR (tests are ok now), or do you want to add more changes?

**Comment by drktfl** [comment]
I think it is ok now. Just cleaning up a bit...

**Pull request merged**
